"""Provider selection and capability detection for the thesis review workflow.

Two audiences run this workflow with whichever agent tool they have: Codex,
Claude, or both (one generates, the other independently reviews). This module is
the provider-neutral contract for *which* provider runs *what*, and for failing
closed when a requested provider or role adapter is unavailable — never silently
degrading to no independent review.

It is pure (no spawning): orchestration stays a provider-neutral role plan, and
the parent session performs the actual launches. These helpers let the parent
(or a diagnostic) resolve the run provider, check availability, and confirm a
role can run under a given provider before it is launched.
"""

from __future__ import annotations

import shutil
from collections.abc import Callable, Iterable

from thesis_review_workflow import agent_profiles

# Requested run providers. ``both`` means generate with one provider and review
# with the other (sequential; see docs/agent-scheduling.md).
RunProvider = str  # "codex" | "claude" | "both"
RUN_PROVIDERS: tuple[str, ...] = ("codex", "claude", "both")

# Executable names probed for capability detection.
PROVIDER_EXECUTABLES: dict[str, str] = {"codex": "codex", "claude": "claude"}


class ProviderError(ValueError):
    """Raised when a requested provider/role combination cannot be satisfied."""


def detect_installed_provider_clis(which: Callable[[str], str | None] = shutil.which) -> tuple[str, ...]:
    """Return the providers whose CLI is on PATH, in stable order.

    This is a presence probe, NOT full readiness: it does not check the CLI
    version or whether required project hooks are active/trusted. Launch-time
    readiness (minimum Claude version, active privacy/write hooks) is validated
    by the parent before a provider is used; see docs/agent-workflow.md.
    """
    return tuple(name for name in ("codex", "claude") if which(PROVIDER_EXECUTABLES[name]))


def provider_can_run_role(provider: str, profile_id: str) -> bool:
    """True if ``provider`` has an adapter for ``profile_id`` in the registry."""
    return provider in agent_profiles.providers_for_profile(profile_id)


def resolve_run_provider(requested: str | None, available: Iterable[str]) -> str:
    """Resolve the run provider, failing closed.

    ``requested`` is the operator's choice (``codex``/``claude``/``both``) or
    ``None`` to auto-select. A single provider must be available; ``both``
    requires both. Raises :class:`ProviderError` with an actionable message
    otherwise — the caller must stop, not proceed without a provider.
    """
    have = set(available) & set(agent_profiles.SUPPORTED_PROVIDERS)
    if not have:
        raise ProviderError("No supported agent provider is available (need the codex or claude CLI on PATH).")

    if requested is None:
        # Auto: prefer Codex (the established path) when present, else Claude.
        return "codex" if "codex" in have else "claude"

    if requested not in RUN_PROVIDERS:
        raise ProviderError(f"Unknown provider {requested!r}; expected one of {RUN_PROVIDERS}.")

    if requested == "both":
        missing = [p for p in agent_profiles.SUPPORTED_PROVIDERS if p not in have]
        if missing:
            raise ProviderError(f"provider=both needs both CLIs; missing: {missing}.")
        return "both"

    if requested not in have:
        raise ProviderError(f"provider={requested} requested but its CLI is not on PATH (available: {sorted(have)}).")
    return requested


def select_role_provider(profile_id: str, run_provider: str, available: Iterable[str]) -> str:
    """Pick the concrete provider that will run one role, failing closed.

    Under ``both``, the role is generated by whichever provider has an adapter
    (preferring Codex) so the *other* provider can review it. A role with no
    adapter for the only viable provider raises :class:`ProviderError` rather
    than silently falling back.
    """
    # Fail closed on availability first: `both` needs both CLIs, a single
    # provider must be present. This rejects e.g. run_provider="both" with only
    # one CLI, where no genuine cross-provider review is possible.
    resolve_run_provider(run_provider, available)
    have = set(available) & set(agent_profiles.SUPPORTED_PROVIDERS)
    candidates = ["codex", "claude"] if run_provider == "both" else [run_provider]
    for provider in candidates:
        if provider in have and provider_can_run_role(provider, profile_id):
            return provider
    supported = agent_profiles.providers_for_profile(profile_id)
    raise ProviderError(
        f"role {profile_id!r} cannot run under provider {run_provider!r} "
        f"(role adapters: {supported or '()'}; available: {sorted(have)})."
    )


def role_provider_matrix(available: Iterable[str]) -> dict[str, tuple[str, ...]]:
    """Map each spawnable role to the available providers that can run it."""
    have = set(available)
    matrix: dict[str, tuple[str, ...]] = {}
    for route in agent_profiles.profile_routes():
        if not route.profile_id:
            continue
        matrix[route.profile_id] = tuple(p for p in route.providers if p in have)
    return matrix
