"""Tests for provider selection and capability detection."""

from thesis_review_workflow import agent_providers


def _which(available):
    have = set(available)
    return lambda name: f"/usr/bin/{name}" if name in have else None


def _raises(fn, *args) -> bool:
    try:
        fn(*args)
    except agent_providers.ProviderError:
        return True
    return False


def test_detect_installed_provider_clis_reads_path() -> None:
    assert agent_providers.detect_installed_provider_clis(_which({"codex"})) == ("codex",)
    assert agent_providers.detect_installed_provider_clis(_which({"claude"})) == ("claude",)
    assert agent_providers.detect_installed_provider_clis(_which({"codex", "claude"})) == ("codex", "claude")
    assert agent_providers.detect_installed_provider_clis(_which(set())) == ()


def test_resolve_run_provider_auto_prefers_codex_then_claude() -> None:
    assert agent_providers.resolve_run_provider(None, ["codex", "claude"]) == "codex"
    assert agent_providers.resolve_run_provider(None, ["claude"]) == "claude"


def test_resolve_run_provider_explicit_requires_availability() -> None:
    assert agent_providers.resolve_run_provider("claude", ["codex", "claude"]) == "claude"
    assert _raises(agent_providers.resolve_run_provider, "claude", ["codex"])
    assert _raises(agent_providers.resolve_run_provider, "codex", [])


def test_resolve_run_provider_both_requires_both() -> None:
    assert agent_providers.resolve_run_provider("both", ["codex", "claude"]) == "both"
    assert _raises(agent_providers.resolve_run_provider, "both", ["codex"])


def test_resolve_run_provider_rejects_unknown_and_empty() -> None:
    assert _raises(agent_providers.resolve_run_provider, "gemini", ["codex"])
    assert _raises(agent_providers.resolve_run_provider, None, [])
    # auto with only unsupported providers present must fail, not return claude
    assert _raises(agent_providers.resolve_run_provider, None, ["gemini"])


def test_provider_can_run_role_reflects_registry() -> None:
    assert agent_providers.provider_can_run_role("codex", "thesis_code_quality_reviewer")
    assert agent_providers.provider_can_run_role("claude", "thesis_code_quality_reviewer")
    # GitHub intake is Codex-only (shell/network) for now.
    assert agent_providers.provider_can_run_role("codex", "thesis_github_code_intake_reviewer")
    assert not agent_providers.provider_can_run_role("claude", "thesis_github_code_intake_reviewer")


def test_select_role_provider_handles_both_and_codex_only() -> None:
    both = ["codex", "claude"]
    # Claude-capable role under 'both' is generated by Codex (so Claude reviews).
    assert agent_providers.select_role_provider("thesis_code_quality_reviewer", "both", both) == "codex"
    # Codex-only role under claude fails closed.
    assert _raises(agent_providers.select_role_provider, "thesis_github_code_intake_reviewer", "claude", both)
    # ...but runs on Codex under 'both'.
    assert agent_providers.select_role_provider("thesis_github_code_intake_reviewer", "both", both) == "codex"
    # 'both' with only one provider present cannot deliver cross-provider review.
    assert _raises(agent_providers.select_role_provider, "thesis_code_quality_reviewer", "both", ["codex"])


def test_role_provider_matrix_filters_by_availability() -> None:
    matrix = agent_providers.role_provider_matrix(["codex"])
    assert matrix["thesis_code_quality_reviewer"] == ("codex",)
    assert matrix["thesis_github_code_intake_reviewer"] == ("codex",)
    matrix_both = agent_providers.role_provider_matrix(["codex", "claude"])
    assert matrix_both["thesis_code_quality_reviewer"] == ("codex", "claude")
